name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node: [ '12', '14', '16' ]
        
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          
      - run: yarn install --frozen-lockfile
      - run: yarn test
